#!/bin/sh

PYTFEEDER_CHANNELS_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/pytfeeder/channels.yaml"
PYTFEEDER_DB_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/pytfeeder/pytfeeder.db"
DOWNLOAD_OUTPUT="$HOME/Videos/YouTube/%(uploader)s/%(title)s.%(ext)s"
PYTFEEDER_FZF_ALL_CHANNELS_LIST=/tmp/pytfeeder_fzf_all_channels_list.txt
PYTFEEDER_FZF_NE_CHANNELS_LIST=/tmp/pytfeeder_fzf_non_empty_channels_list.txt
PYTFEEDER_FZF_CHANNELS_LIST=/tmp/pytfeeder_fzf_channels_list.txt
FEED_LIMIT=100

if [ ! -f "$PYTFEEDER_CHANNELS_PATH" ]; then
    echo "config file $PYTFEEDER_CHANNELS_PATH not found"
    exit 1
fi

if [ ! -f "$PYTFEEDER_DB_PATH" ]; then
    echo "db file $PYTFEEDER_DB_PATH not found"
    exit 1
fi

yq -r '.[] | select((.hidden // false) == false) | .channel_id+" "+.title' \
    "$PYTFEEDER_CHANNELS_PATH" >"$PYTFEEDER_FZF_ALL_CHANNELS_LIST"

_ids=$(awk '{r = r (NR==1 ? "" : ",") "'"'"'" $1 "'"'"'" } END { print r }' \
    "$PYTFEEDER_FZF_ALL_CHANNELS_LIST")

sqlite3 <. -init /dev/null -column "$PYTFEEDER_DB_PATH" "\
    SELECT channel_id FROM tb_entries \
    WHERE is_deleted = 0 and channel_id IN ($_ids) \
    GROUP BY channel_id" >"$PYTFEEDER_FZF_NE_CHANNELS_LIST"

[ -f "$PYTFEEDER_FZF_CHANNELS_LIST" ] && printf '' >"$PYTFEEDER_FZF_CHANNELS_LIST"

echo feed\ Feed >"$PYTFEEDER_FZF_CHANNELS_LIST"
while IFS= read -r line; do
    if grep -qx "${line%% *}" "$PYTFEEDER_FZF_NE_CHANNELS_LIST"; then
        echo "$line" >>"$PYTFEEDER_FZF_CHANNELS_LIST"
    fi
done <"$PYTFEEDER_FZF_ALL_CHANNELS_LIST"

select_query() {
    if [ "$1" = feed ]; then
        cat <<EOF
        SELECT id, is_viewed, title FROM tb_entries
        WHERE  is_deleted = 0
        AND channel_id IN ($(
            yq -r '[.[] | select((.hidden // false) == false) |
            ("'\''" + (.channel_id|tostring) + "'\''")] | join(", ")' \
                "$PYTFEEDER_CHANNELS_PATH"
        ))
        ORDER BY published DESC
        LIMIT $FEED_LIMIT
EOF
    else
        cat <<EOF
        SELECT id, is_viewed, title FROM tb_entries
        WHERE is_deleted = 0 AND channel_id = '${1}'
        ORDER BY published DESC
EOF
    fi
}

# shellcheck disable=SC2016,SC2059
while :; do
    channel_line="$(fzf --with-nth 2.. --preview='' <"$PYTFEEDER_FZF_CHANNELS_LIST")"
    [ -n "$channel_line" ] || exit 0
    channel_id="${channel_line%% *}"
    channel_title="${channel_line#* }"

    selected_line="$(
        echo __go_back__ |
            sqlite3 <. -init /dev/null -column "$PYTFEEDER_DB_PATH" \
                "$(select_query "$channel_id")" |
            while read -r line; do
                line=$(echo "$line" | tr -s ' ')
                id="${line%% *}"
                is_viewed="$(echo "$line" | cut -d' ' -f 2)"
                title="$(echo "$line" | cut -d' ' -f 3-)"
                if [ $is_viewed -eq 0 ]; then
                    printf '%s \033[1;32m%s\033[0m\n' "$id" "$title"
                else
                    echo "$id $title"
                fi
            done | fzf --ansi --ghost="$channel_title" \
            --header='[esc,ctrl-q]: Go back, [ctrl-space]: Play' \
            --bind='ctrl-space:execute-silent(\
    notify-send -i youtube -a pytfeeder "Playing \"$(echo {} |\
    sed "s/^[-_0-9a-zA-Z]\{11\}[ \t]*//;s/[[ \t]*$//")\"..." &&\
    setsid -f mpv "https://youtu.be/$(echo {} | cut -d" " -f1)" >/dev/null 2>&1)' \
            --with-nth 2.. --preview=''
    )"

    [ -n "$selected_line" ] || continue

    vid_id="${selected_line%% *}"
    vid_title="$(echo "${selected_line#* }" | sed 's/^[ \t]*//; s/[ \t\n]*$//')"

    [ -n "$vid_id" ] || exit 0
    notify-send -i youtube -a pytfeeder "⬇️Start downloading '$vid_title'..."
    qid="$(tsp -L pytfeeder yt-dlp "https://youtu.be/$vid_id" -o "$DOWNLOAD_OUTPUT")"
    tsp -D "$qid" notify-send -i youtube -a pytfeeder "✅Download done: '$vid_title'" >/dev/null 2>&1
done
