DEFAULT_CHANNEL_FEED_LIMIT = 15
DEFAULT_FEED_LIMIT = 100
DEFAULT_CHANNELS_FMT = "{title}\000info\037{id}"
DEFAULT_ENTRIES_FMT = "{title}\000info\037{id}\037meta\037{meta}"
DEFAULT_DATETIME_FMT = "%D %T"
DEFAULT_OFFSET = 1
DEFAULT_SEPARATOR = "\n"
